### ISSUE TITLE
🚀 Exciting News: Announcing Daikin Europe Developer Portal! 🚀

### ISSUE THREAD

**Issue by Daikin-Europe** [rospogrigio/daikin_residential#182]
Dear Developers and Tech Enthusiasts,

We are thrilled to announce the new Daikin Europe Developer Portal. This platform is dedicated to empowering developers like you to unlock the full potential of Daikin air2air and air2water heat pumps, fostering innovation in the world of climate control.

🌐 **What is the Developer Portal?**

Our Developer Portal is your gateway to a world of endless possibilities with Daikin products.
Whether you're an experienced developer, a company exploring opportunities or just starting your coding journey, this platform is your ultimate resource for building and integrating with our technologies.
It's a one-stop destination for all things development-related, offering documentation and resources to supercharge your projects.

🛠️ **Key Features?**

📚 Comprehensive Documentation: Access documentation that provide a deep dive into our APIs, ensuring you have everything you need to get started and excel with your integration.

🚀 Interactive API Explorer: Experiment with our APIs in real time using our interactive API explorer, making the integration process smooth and intuitive.

🔌 Easy integration: Integrate directly onto the Onecta ecosystem with your own units to develop or test your integration. No special hardware required!

🔑 Rate Limitation: To continue offering the Onecta API for free to all our customers a default rate limitation will be implemented.

💼 B2B Business Case Validation: Explore hassle free if your companies business case works together with the Daikin APIs. Get in contact with us when you want to become a partner.

 

🚧 **What's Next?**

This is just the beginning! We're committing to expand and enhance our Developer Portal, with new features and resources in the future.
Your feedback and suggestions will be invaluable as we evolve the portal to meet the needs of our customers.

:wrench: What changes can already be prepared from your application?
Make your current application compatible with the upcoming rate-limitation of 150 calls/day. This will allow everyone to query at least every 15 minutes for temperature changes in their home of all their devices. Temperature variation in the home is often not so fast that a faster update rate is required. 

 

🌟 **Ready to Get Started?**

We're targeting beginning 2024 for the first access to the Daikin Europe Developer Portal. With later in Q1-2024 the release of self service within the developer portal. 
Get ready to innovate, build, and make a lasting impact with our Developer Portal. We can't wait to see the incredible solutions you'll create!

Stay tuned for more !

[Daikin Europe]( https://www.daikin.eu/en_US/product-group/control-systems.html#tabs-961122979a-item-3ec4749e36-tab )

**Comment by jwillemsen** [comment]
Great news @Daikin-Europe ! Hopefully there will be much more information available from the Daikin devices, especially from the Altherma 3 device I would like to see much more details!

**Comment by rospogrigio** [comment]
Thank you @Daikin-Europe . I have created a new PR #183 that reduces the polling time to every 15 minutes, as you suggested, for everybody to try.
A couple of questions: is there (or will be in the future) the possibility to send commands locally in the LAN instead of passing through the cloud? Many users (including myself) have been asking for this. Thank you for letting us know.

**Comment by jwillemsen** [comment]
A rate limit of 150 calls is enough for an AC unit, but not for an Altherma, those change much faster, would love to see a higher rate there

**Comment by VolkerH** [comment]
As @rospogrigio said,  implement local network access!
 Rate limiting is a no-go if you don't provide it. 
I bought and my airconditioning systems specifically because they can be controlled via Wifi. This was listed as a feature of the device when i bought it (not as an optional service),  you can't take it away after I paid for it. 
I use Home Assitant together with Zigbee sensors to implement my own thermostats. This is for 5 devices. If querying and setting a state is one API access each, that already requires 10 calls for 5 devices. 
I don't see why there should be any limit at all.

**Comment by jwillemsen** [comment]
For the Altherma there is a separate HA integration, at some point I want to extend that integration also with support for the AC devices, see https://github.com/speleolontra/daikin_residential_altherma

**Comment by Apollon77** [comment]
@Daikin-Europe Cool, good news, keep us updated. But basically I agree to the discussed topics above about rate limits vs local access.

**Comment by barryvdh** [comment]
1 update per 15 minutes seems a bit low ..? My AC goes from 18 to 23 degrees in 15 minutes (small room).. 

I can understand limiting to 1 call a minute (instead of 15 seconds) or 150 change operations/day (setting temp/hvac mode), but it's also about showing the actual state in Home Assistant (current/target temperate, hvac mode, on/off), so 15 minutes seems a long time to reflect the current state on your dashboards, which means the dashboard is not really useful.

Thanks for the Developer API though, just hope it doesn't cripple the HA integration, instead of making it better..

**Comment by VolkerH** [comment]
To elaborate on my earlier comment. Maybe I am jumping the gun here, but this announcement seems like a crass form of corporate language to me. DAIKIN describing a serious deterioration in thier product as a great new feature for developers. Maybe my concern is unfounded, but there are recent examples of other companies ... this is called _enshittification_ https://doctorow.medium.com/the-enshittification-of-garage-door-openers-reveals-a-vast-and-deadly-rot-eed85da5b0ba

As for the corporate speak: you are not _making sure you are able to continue this free service_. This is not a free service. As customers, we already paid for this feature, so it is not free. I paid for a device, I didn't subscribe to a service. In my case, I paid a 5 digit EUR sum for DAIKIN devices.

There is no technical reason for denying local access. This is proven by my  Comfora unit with the older WIFI modules (if I had known I would only have installed the _cheaper_ Comfora units and not the more expensive, newer units). Local access works well, no cloud needed (so no cost for DAIKIN to run servers for a "free" cloud service most customers don't want). The only reason to make cloud mandatory is to grab data and lock us into using their apps. The `B2B` stuff in combination with the rate limiting suggests to me that any access with more than 15 min interval access will either be through Onecta or some subscription based model. So, we're being dis-owned of our devices for which we paid! I would hope DAIKINs business model is about selling good hardware, not about dealing/collecting in data and selling subscriptions to their API. I would love it if @Daikin-Europe  proves my suspicions wrong and enables local access.

Since my last comment, I found this https://github.com/revk/ESP32-Faikin and ordered several of the pre-assembled PCBs. I fear this will be the only way to truely own the DAIKIN devices that I paid for. But again, please prove me wrong @Daikin-Europe .

To all the others who left ❤️ emojis, please re-read the announcement carefully, with the garage door enshittification in mind and your translator for corporate speak turned to "on". There needs to be massive push-back against @Daikin-Europe  disowning its customers.

**Comment by rospogrigio** [comment]
Yes @VolkerH , I see a common trend with several other IOT vendors about this, that set up everything to be cloud-oriented, and then they realize how high is the cost for them to maintain the cloud connection, and consequently start cutting off the service. My Xiaomi vacuum cleaner, for example, now no longer shows the real time map if you make too many requests, and so we users needed so setup a hack within HA in order to reduce the calls and stay within the rate limitation. I really don't understand this approach, as you say local access is faster and more secure. Cloud connection is nice to have as an add-on, but shouldn't be the only way to interact with the device on the network. Just my 2 cents, let's wait and check wheter @Daikin-Europe want to reply something.

**Comment by rgerhards** [comment]
I guess @Daikin-Europe will never reply here. Just dropped the "bad news PR".

BTW: the same also happened to the VW API for their electric cars. And there even is an annual subscription fee for "connected services".

I am/was thinking about purchasing an Altherma. I am now reconsidering. Albeit is is becoming really hard to own any hardware I paid for. General trend.

**Comment by pjgoodall** [comment]
No Faikin for FTXM71WVMA with wifi controller BRP084C44. Restricting API call frequency to 15m shows that the whole ‘cloud only’ drive was marketing not engineering or customer based at Daikin. Marketing people should only be in meetings at a ratio of 1 in 5. There should never be rooms with only marketing people in them. 
So how does the cloud-centric control go when Optus falls flat during a 40c heatwave?

**Comment by rospogrigio** [comment]
> The more interesting question from my perspective is how that should work withthe Onecta App? All the non tech users will use the app whenever they want and expect current data ... So the App-API will then maybe not have such rate limits (because honestly else normal users will make big noise) , but an "open API" will have? This also makes not that much sense ...

I believe the app will be allowed to perform more frequent polling, or possibly it would update -let's say- every 5 minutes and I highly doubt that anyone would notice. Still would be nice from @Daikin-Europe to have some answers to all the questions asked in the thread so far... but they just threw the stone and hid their hand, as we say in Italy 😉

**Comment by RadianM** [comment]
If polling for dashboard status updates is rate-limited to the imposed maximum of 150 calls/day, that doesn't seem to leave sufficient 'bandwidth' for actual commands? I want to use automations to operate the A/C under my own scheduling and these additional calls would be on top of those performing the 15m polling. And how does this all work out when multiple A/C units are being polled?

**Comment by rospogrigio** [comment]
If all the units are connected to the same account, with each polling you get the data from all the units so don't worry for this. But you do are right when you say that each command you send is a call that goes on top of the polling commands.

**Comment by RadianM** [comment]
> each command you send is a call that goes on top of the polling commands

In which case it would definitely appear that we need a way of setting the polling rate as has been suggested. Personally I think I will be removing the cards from the dashboard as such stale information is offensive.

I also wonder if the 'too frequent' polling is what is affecting my use of the Onecta app to control the A/Cs? I don't know if it's a general thing but the response time is lousy when using the app - very often a new setting does nothing and then shortly after the displayed new setting reverts to how the device was. A frequent culprit is "Powerful mode" which needs several goes at selecting it before it engages.

**Comment by rgerhards** [comment]
> I also wonder if the 'too frequent' polling is what is affecting my use of the Onecta app to control the A/Cs? I don't know if it's a general thing but the response time is lousy when using the app - very often a new setting does nothing and then shortly after the displayed new setting reverts to how the device was. A frequent culprit is "Powerful mode" which needs several goes at selecting it before it engages.

I noticed that problem as well. I "fixed" it by increasing the polling time to 90 seconds inside the current code. I think the value is definined in _init_.

**Comment by RadianM** [comment]
> I noticed that problem as well. I "fixed" it by increasing the polling time to 90 seconds inside the current code. I think the value is definined in _init_.

So this lends support to having a user-adjustable polling time. At the moment, this integration would appear to be interfering with my domestic heating system.

**Comment by shermozle** [comment]
The rate limits seem substantially low, and if this is a problem removing local API access seems like you're intentionally removing a great number of use cases. Let me explain my use case (via Home Assistant):

* Every minute, my solar power inverter tells me how much power was generated vs consumed
* If I have >1,000W of energy being exported, I set the thermostat 4º lower than the target
* If I have <1,000W of energy being exported, I set the thermostat to the target

This means I can pre-chill my house while the sun is shining to give us good comfort with no or low energy usage in the evening, while accounting for variable solar input and variable other loads. When the dishwasher is running its heater, the air con temperature is allowed to warm up a bit.

**Comment by cypherbits** [comment]
Does these rate limits mean that someone can start the AC from Onecta or IR and Home Assistant will only know after 15 minutes?

That is shit @Daikin-Europe .

Where is the local control we wanted for months that do not suppose a cost for your cloud?

**Comment by jwillemsen** [comment]
I have to come back on my previous comment, a rate of 1 times per minute still looks slow when the AC is controlled through onecta and monitored through HA, a rate of 1 times per 10 minutes is really too slow

**Comment by RadianM** [comment]
IMO It's all a bit of an unpleasant mess now. I suspect the choice of rate limiting to 50/day has been set by them to cover half-hourly dynamic energy pricing. It's not been chosen with a view to real time monitoring but for slow 'smart grid' applications. Ultimately this is my goal so I can live without the 'nice to have' dashboard integration. But I'll be sad to have to remove it. And it definitely rules out fine-grained adaptive solar PV integration.

My family wouldn't appreciate losing control using the Onecta app on their smartphones - otherwise the brilliant [Faikin](https://github.com/revk/ESP32-Faikin) would be my go-to solution.

I currently have polling from HA set to every 5 minutes and it's still getting the 288 calls a day through OK. The Onecta app is still a bit laggy but I don't feel it's any worse than before I started using this integration.

**Comment by barryvdh** [comment]
> My family wouldn't appreciate losing control using the Onecta app on their smartphones - otherwise the brilliant [Faikin](https://github.com/revk/ESP32-Faikin) would be my go-to solution.


Depending of the availability of the S21 port, I think you can use both? Eg. the Perfera has built-in Wifi for Onecta, so adding Faikin would allow both Onecta and direct Faikin control I think?

**Comment by RadianM** [comment]
> Depending of the availability of the S21 port, I think you can use both?

Possibly, - I know there's a modbus adaptor available for most indoor units and I had the impression both could co-exist.

**Comment by Gtwizzy** [comment]
Is there any updated release ETA on this yet?

**Comment by eskey0** [comment]
Commenting just to note that, while is honourable that Daikin is trying to acommodate some "extreme cases", as others already said that feels way underwhelming.
Just for reference, I have my units at home, I do have a HA at home, today they have a downtime from 8am to 4pm (or something like that, don't quote me), while that downtime I CANNOT control my units.

I am sorry this is not acceptable, sadly after expending a good amount of money for the WIFI module, I see myself looking for fakin and the likes.

**Comment by cypherbits** [comment]
Yeah, me too, can't control my units right now for maintenance reasons. 
When is the local control coming @Daikin-Europe ?

**Comment by Webreaper** [comment]
It's absolutely absurd that scheduled maintenance takes 8+ hours. An hour I could understand, but this is nuts.

At least I can use the MMI.

**Comment by VolkerH** [comment]
Maybe they neeed 8h to implement the rate limit ?

5 Units. Spot the old model that still supports local control:

![image](https://github.com/rospogrigio/daikin_residential/assets/2210044/1d4a6b41-547e-4e67-ab59-0c7bc52b4e01)

In case @Daikin-Europe are still monitoring this issue, here is some suggested reading from the FTC (in the US, but maybe the EU thinks along similar lines and introduces some regulatoin with big fines):
https://www.ftc.gov/business-guidance/blog/2016/07/what-happens-when-sun-sets-smart-product

![image](https://github.com/rospogrigio/daikin_residential/assets/2210044/56368e5a-861c-4182-b3da-d7ba54a92ee9)

**Comment by barryvdh** [comment]
Might be good if Daikin takes a look at the commotion caused by Haier;
https://www.theregister.com/2024/01/22/haier_plugin_takedown/
https://tweakers.net/nieuws/217750/haier-stuurt-takedownverzoek-aan-home-assistant-plug-inontwikkelaar.html (Dutch)
https://github.com/Andre0512/hon/issues/147#issuecomment-1902075829

**Comment by RadianM** [comment]
Unfortunately, while I totally agree with all the points made above, my legal mind tells me there's nothing particularly compelling towards them providing fairer use. What I'd really like to understand is the reason a local rest interface isn't provided anymore? Some aspects are still there - the debug endpoints and license page are still present. Running debug creates a bunch of files that make it clear how many useful pages have gone - all over local network.

Can anyone explain how it benefit the company to disallow local access? If it's because they might lose usage statistics and monitoring, are they really concerned about people blocking WAN access and losing that information? People who don't bother with setting up wifi for their devices fall into the same class of user.

**Comment by rospogrigio** [comment]
@RadianM which debug endpoints are you talking about? Can you explain?
I don't really see the benefit in removing the local access too, hope @Daikin-Europe will reply one day...

**Comment by RadianM** [comment]
> @RadianM which debug endpoints are you talking about? Can you explain? I don't really see the benefit in removing the local access too, hope @Daikin-Europe will reply one day...

The license page is served directly from the IP address of the device. In the Onecta App, on the main page under More>Settings>Diagnostics - starting that process returns a zip containing a number of files. The json and gateway endpoints list all the features of the devices but these all appear to be routed via the cloud server.

**Comment by Daikin-Europe** [comment]
🚀 Exciting News: The Daikin Europe Developer Portal now available! 🚀
It is with pleasure that we announce that the new Daikin Europe Developer Portal is now available for use!
This platform is created to empower developers like you to unlock the potential of Daikin air-to-air and air-to-water heat pumps.
 
🔧 What about existing open-source integrations?
 To ensure a seamless experience and to take advantage of the new platform, we kindly request all users/developers with existing integrations on the Daikin Onecta platform to migrate their setups within the next 30 days.
From 11 March onwards, we'll deprecate the currently used API key found in many open-source projects. This means existing integrations will stop functioning.
 
🚧 What's next for the Developer Portal?
 This is just the beginning! We're committing to expand and enhance our Developer Portal. Expect new features and resources in the future!
In a following update we want to bring a developer self-service functionality, allowing developers to create their own application credentials.
 
🙏 Thank you for your continued support and for being an integral part of the Daikin community.
We appreciate all your feedback posted on GitHub and through other channels. We will process and evaluate this input for future updates of Daikin Products and the Developer Portal.
We’re looking forward to witnessing the incredible projects and innovations that you are about to create!
 
🔗 Explore the portal now: [Daikin Europe Developer Portal](https://developer.cloud.daikineurope.com/login)
 Daikin Europe

**Comment by barryvdh** [comment]
Hmm it's slightly improved, from 150 to 200.

> This rate limit configuration allows you to send a maximum of 200 requests per day to the ONECTA Cloud API. Furthermore, per minute, a maximum of 6 requests can be sent. This rate limitation gives you the possibility to query the state of your devices periodically while keeping the flexibility to perform sufficient actions on your devices.
For example, if your application would fetch the state of your devices every 10 minutes, this would take up 144 API requests over a window of 24 hours. Note that you can request the state from all devices with only one API request. You then still have 56 requests that you can use for other actions such as changing the operation mode or room temperature setpoint during this window. However, you can't perform these actions too quickly after each other because you only have a budget of 6 requests per minute.
The API rate limit algorithm is implemented using a sliding window policy, which dynamically tracks and manages the number of requests made within specific time intervals.
In a sliding window approach, time is divided into consecutive intervals, often referred to as windows. Unlike a fixed window where the limit resets at regular intervals, the sliding window maintains a moving time frame that continuously shifts forward.
For example, if we consider the rate limit of 6 requests per minute, the sliding window constantly tracks the requests made within the last minute. Each time an API call is made, only those requests are taken into account to calculate the remaining budget. This dynamic shifting ensures that the rate limit is calculated over a rolling time period rather than a fixed reset point.

So every user needs its one API key? Which is not a problem per se I guess, but 1 month might be a little fast to implement the redirect flow and have all the users update their integrations..?

**Comment by tetele** [comment]
Good think you listened to what people said about local control @Daikin-Europe

**Comment by jwillemsen** [comment]
> 🔧 What about existing open-source integrations? To ensure a seamless experience and to take advantage of the new platform, we kindly request all users/developers with existing integrations on the Daikin Onecta platform to migrate their setups within the next 30 days. From 11 March onwards, we'll deprecate the currently used API key found in many open-source projects. This means existing integrations will stop functioning.

As you know your API the best and there are several projects that use the existing API it would be much more helpful when you would convert at least one integration to the new model, that way you know also whether the new model works ;-)
 
> 🚧 What's next for the Developer Portal? This is just the beginning! We're committing to expand and enhance our Developer Portal. Expect new features and resources in the future! In a following update we want to bring a developer self-service functionality, allowing developers to create their own application credentials.

That really depends on the data Daikin provides, with the limited data available integrations can't do much more more. We lack for example data to calculate a COP, see all Altherma sensors, etc. A rate limit of 200 calls per day is not really much when you want to control all devices. As remarked several times, a local API would be much more helpful.

**Comment by Webreaper** [comment]
> We lack for example data to calculate a COP

It does seem crazy that the key measurement we'd want from the heat pump, i.e., COP, isn't available to track via the API. The only way I can monitor my COP is to remember to go to the MMI and write down the total energy use figures, and track them in a spreadsheet. Totally absurd, Daikin!

**Comment by rospogrigio** [comment]
@Daikin-Europe , are you even considering to provide local LAN control as was available on older models? Can you please give a word about this request? Just to know whether it's something we can expect in the future or whether you're not willing to make it available. Also knowing the reasons behind the choice would be nice.
Thank you

**Comment by Apollon77** [comment]
@Daikin-Europe As one of the affected developers with a relevant userbase of smart home users using this (and also an owner of Daikin devices) - is there any interest or way to get a personal contact to discuss your approach and the limits? In fact you thank us as baing part of the community, but it seems that you are not part of it yourself ... Community is about communication and collaboration but unfortunately Daikin is very unresponsive here in this thread and also in all the tries I did personally before to get a contact to discuss integrations. I would really be happy to start a discussion with you guys to find the best approaches for the Daikin community! Come one ... jump over your shadow and lets talk ... lets work together!

For the Limits
In fact the Limits with 200 calls /day we end up with one call per 7,2 aka 8 minutes - as you already calculated in your infos ... If it would only about getting the currenmt data honestly that could in theory work out ... BUT the reality is that for each controlling action an integration needs to query the device status after the action to update the details. If you now really consider people using the Daikin devicees to heat (or cool) their houses and partially mix devices (so it is not only Daikin devices relevant) or react to someone opening a window to turn off the device or using boost modes to heat faster then usual and and and then for all such use cases this is not enough. Because if I now calculate some reserves in here for this then it means that I can use maximum a third of 200 for "status updates" and the rest is "control+request of status afterwards" reserve for controlling the system. This end then with status update every 24mins ... lets say 30 mins to have reserves for controlling operations.
When I heat my room with Daikin device for 30 minutes I end up in a way too warm room if I have no control to react on things ...
In my eyes 56 requests left - as your own text states @Daikin-Europe with knowing that we need to "read" after every "write" we end up with 28 control operations for a whole day ... This might work for a static "app controlled home" but not for a bit more enhanced smart home operations and logics.

So having 500 calls/day ... or at least 400 ... could be maybe a better idea then 200 ... but in fact any limitation is  a downside.

Re local operations: maybe somewhen Daikin adds Matter as protocol ... It would be much cheaper then operating an own Cloud system these days :-) maybe something to think about in the Daikin prodict management and tech departments :-)

**Comment by rgerhards** [comment]
@Daikin-Europe If you insist on cloud only, I would even be willing to pay a modest fee to use it with a much higher rate limit that actually permits to control the device.

I am doing the same with Davis Weatherstations, and I do so in additition to the local interface they offer. Simply because the cloud has some benefits in here.

All in all, I agree to everyone else here. Enforcing cloud use and then crippeling it to a point where it becomes unusable for real home automation is not a smart move.

**Comment by f0rdprefect** [comment]
@Daikin-Europe a user of the homeassistant integration here: For me you borked the control via the oneta app for the last 24hrs or so. I specifically bought daikin, because I believed I had a good homeassistant support, taking my chances to get either local or cloud control. Last summer everything worked perfectly until you imposed the rate limit.

So not only you do enforce the cloud. You also broke it and leave me stranded with the strong incentive to buy two faikin controllers and void my warranty in order to own my HVAC units again. Would I recommend Daikin products to friends right now? Not likely!

**Comment by jwillemsen** [comment]
@Daikin-Europe Looking at the documentation is it correctly determined that the user has to login at Daikin Cloud and not specify the user/password within the HA setup dialog? How does this work for python scripts which don't have a user interface?

**Comment by simonebortolin** [comment]
> @Daikin-Europe Looking at the documentation is it correctly determined that the user has to login at Daikin Cloud and not specify the user/password within the HA setup dialog? How does this work for python scripts which don't have a user interface, for example the helper scripts at https://github.com/rospogrigio/daikin_residential/tree/master/tools. I wanted to convert these to the new API, that would be much easier to test as through Home Assistant, started with that at https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-daikincloudcontroller/tools

Like smallstep sso: https://smallstep.com/sso-ssh/

you make a webserver in localhost that implements OIDC, log in via idp daikin, and then return to the application. Not a bad idea. It's better than saving your username and password who knows where

**Comment by barryvdh** [comment]
I think it's basically an OAuth 2 implementation, right? So https://developers.home-assistant.io/docs/core/platform/application_credentials/ where you would indeed trigger a popup to login, and receive the token in the callback.

**Comment by jwillemsen** [comment]
Any help migrating to the new API authorization mechanism is welcome! My time is pretty limited the coming weeks due to other obligations

**Comment by jwillemsen** [comment]
Looks the approach to try to get the scripts working is not the best one. Need to rework the code to use the application_credentials support from HA, that looks to be easier, hopefully someone reading here has experience with that.

**Comment by Apollon77** [comment]
In fact yes the Authentication is an OpenID/Oauth flow ... all pretty standard stuff ... So  you need to store the tokens and potentially refresh the access token and such ... also Standard OAuth stuff.

**Comment by jwillemsen** [comment]
Maybe you can assist @Apollon77 with this? For me this is all new stuff, not my daily job ;-)

**Comment by hmaki** [comment]
@Daikin-Europe Thanks for the info. I looked up on the API description, specifically the gateway-devices what sensory data it is going to offer. I don't know if this is a complete set as it seems to refer to Altherma in few places, but I would really like to consume the sensory data that I can now get through [https://github.com/jwillemsen/daikin_residential_altherma](https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-haoauth2)

namely: fanMotorRotationSpeed, heatExchangerTemperature and suctionTemperature.

On Air-to-air these can be used to calculate the COP (when measuring the real-time power consumption separately from plug or switchbox).

Also if possible the outdoor unit's heatExchangerTemperature would be nice.

**Comment by jmtatsch** [comment]
@Daikin-Europe while we are at it, why not offering the real-time power consumption as a value as well instead of aggregated values.

**Comment by jwillemsen** [comment]
Got a little bit further, I am able to let HA do the authorization call to Daikin but the redirect_url seems to be fixed, I think I need to tweak that, but Daikin doesn't allow that at this moment, see https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-haoauth2 for the work in progress

**Comment by barryvdh** [comment]
Nice! Sorry I can't really help much, no experience with python. But happy to test something if required.

**Comment by jwillemsen** [comment]
It look the amount of data provided by Daikin with the new cloud API has decreased, with the old API for my home installation (Altherma and a Daikin AC 4 unit split) I have 5 devices and 300 entities, with the new API I have 5 devices and only 190 entities

**Comment by jwillemsen** [comment]
See https://github.com/jwillemsen/daikin_residential_altherma/pull/33 for a draft pull request

**Comment by jwillemsen** [comment]
@hmaki Do you have your own integration or are you testing my draft PR?

**Comment by hmaki** [comment]
I was trying this out using browser and some other tools to generate the token and then used the Daikin's API portal to test out the /gateway-devices endpoint.

**Comment by jwillemsen** [comment]
See my draft PR, listed a few there

**Comment by Gisbert1** [comment]
"From 11 March onwards, we'll deprecate the currently used API key found in many open-source projects. This means existing integrations will stop functioning."

PLEASE CONTINUE THE CURRENT API KEY !!!

**Comment by henri98** [comment]
@Daikin-Europe, why only control via the internet?

A local API would be much better architecturally. Then there are no dependencies that can be unavailable/unreliable. **Please bring back the local api!**

**Comment by jwillemsen** [comment]
@Daikin-Europe Any plans to provide a test account to integration developers which has all kinds of Daikin devices so that people can test their integration using that test account?

**Comment by Apollon77** [comment]
@Daikin-Europe Please answer to my email ... This afternoon it is 7 days ago that I wrote you to the address listed in your developer portal to dicuss about rate limits. No answer so far ... means 30-7 =23 days left. If you set such short timelines you should also react to emails please!

**Comment by tetele** [comment]
I honestly don't think they'll ever respond, just as they haven't responded after the first bomb drop in November. They "did whatever they could", i.e. notified developers and went about their business (which apparently is saving big bucks with cloud services, now that nobody can control their HVACs).

Best we can do (apart from modding our existing AC units) is to recommend other AC brands to people asking us what to get.

**Comment by simonebortolin** [comment]
For local API: https://github.com/revk/ESP32-Faikin and https://github.com/raomin/ESPAltherma and frankly it is better mqtt than plain HTTP, which for me, however, do not fully replace cloud api.

**Comment by jmtatsch** [comment]
@Daikin-Europe I really liked the alterma 3 lineup and thus wanted to buy one in addition to my existing aircondition unit. I also wanted to buy some stocks in your company because I was convinced of the technological superiority of your products. Needless to say, I will bring my business and investment elsewhere if there is no 180 degree policy change here.

**Comment by Raspdomo** [comment]
> A rate limit of 150 calls is enough for an AC unit, but not for an Altherma, those change much faster, would love to see a higher rate there

It's not enough for an AC unit either. I steer mine depending on excess power production from my solar panels. I have one call per minute (during daylight) ! Could reduce that a bit, but 150 call/day would still be far below my needs...

**Comment by Raspdomo** [comment]
> The rate limits seem substantially low, and if this is a problem removing local API access seems like you're intentionally removing a great number of use cases. Let me explain my use case (via Home Assistant):
> 
> * Every minute, my solar power inverter tells me how much power was generated vs consumed
> * If I have >1,000W of energy being exported, I set the thermostat 4º lower than the target
> * If I have <1,000W of energy being exported, I set the thermostat to the target
> 
> This means I can pre-chill my house while the sun is shining to give us good comfort with no or low energy usage in the evening, while accounting for variable solar input and variable other loads. When the dishwasher is running its heater, the air con temperature is allowed to warm up a bit.

My implementation is quite similar to yours. I poll my units once per minute. Setpoint updates and on/off commands go on top of that...
I do not understand at all why Daikin would close down the local API option. It doesn't cost them anything to leave it as is... Any IT professional will confirm that controlling local units over the internet instead of a local API just adds an unnecessary complexity and dependency. Once again the "cloud hype" tends to kill a perfectly fine and straightforward solution...

**Comment by simonebortolin** [comment]
> I do not understand at all why Daikin would close down the local API option. It doesn't cost them anything to leave it as is... Any IT professional will confirm that controlling local units over the internet instead of a local API just adds an unnecessary complexity and dependency. Once again the "cloud hype" tends to kill a perfectly fine and straightforward solution...

The local API is closed on all third gen adapters (rev C), in rev A and B it is open, this is thanks to the parent company, there is a post on HA explaining this https://community.home-assistant.io/t/daikin-integration-updated-2022-09-26/431819

for example haier (see: https://github.com/Andre0512/hon) also has a similar problem, which is that cloud APIs have a huge cost for them as they pay per HTTP call, ideally they would do something in MQTT

**Comment by tomlut** [comment]
Cloud control is a nice to have for some, but local control is a **necessity**. 

Removing the local API is not a smart move. It will certainly make me look elsewhere when it comes time to replace my heat pumps. And to be clear I am not in Europe and am not affected by this.

**Comment by Apollon77** [comment]
Without being the "devils advocate" partly I can understand companies that close local interfaces. In fact the reality is that customers expect that they can also control their devices when not being at home - especially the "not that technical" guys. This means that a company like Daikin need to have a cloud access solution anyway available to address this need/requirements from a "majority" of their customers. This ends in having to maintain a local API and a cloud one in the firmwares but ideally also in their Apps and such. So this is an "effort" point that simply costs developer resources.

With this in mind it could sound "cheaper" to simplify the WLAN hub in the devices and just offer the cloud solution. I think the user group of smart home enthusiasts is simply not huge enough to matter in general ... So in fact Daikin as one of the only ones wants to offer a developer portal to allow also other usecases to be implemented. This is also a bit unique when you see many other big players out there. Yesthe communication from Daikin is not optimal here, but lets see what comes.

Sure I personally as a tech guy also would love to have local APIs that can be used without limits because then we all would not need to use cloud solutions ... but in fact there are always two sides of the story ...

As said: In an ideal world it would all get Matter somewhen which mean local control and the cloud access could simply be "outsourced" to Apple, Google or Amazon ;-)

**Comment by simonebortolin** [comment]
> As said: In an ideal world it would all get Matter somewhen which mean local control and the cloud access could simply be "outsourced" to Apple, Google or Amazon ;-)

No. I want to be as independent as possible from the big giants.

**Comment by Apollon77** [comment]
matter is hopefulyl becoming the new standard ... so Expect that there will be many controllers available also in your TV and such ... so you should have options to choose from ...

**Comment by Webreaper** [comment]
> No. I want to be as independent as possible from the big giants.

Tbh, I'm ambivalent. What I want is a good, usable, functional API that does what I need, is well supported, and works. I understand the commercial reasoning for not supporting local APIs (people may subvert validation checks, and you get all sorts of warranty issues).

So if Daikin, Solis et al produce good APIs that allow us to drive automation, I don't care if it goes via their cloud or not - as long as they don't cut us loose in future and suddenly cease support etc. But I think with a company the size of Daikin, that's less of an issue.

**Comment by Raspdomo** [comment]
@Apollon77: I share your "devils advicate" opinion. There are indeed two sides, and no company wants to cope with the "not that technical guys" who often tend to consume lots of support/helpdesk energy, But there are tech guys like you who dispose of a thorough and proven knowledge on the matter, and it's a pity (not to say a shame) that even you don't get into dialog with them... As an IT professional myself I've always considered it a necessity - and a privilege - in any project to have a selection of experienced users to rely on for both analysis and testing. Daikin seems to know it all better by themselves - but the limit of 150/200 calls per day is enough to prove that they don't.

I also like your ideas about Matter (even though I don't really matter about Matter myself :-). A company should focus on it's core business (Daikin = heat pump devices) and outsource non-core stuff to other players in the market.

I wouldn't know how, but is there a way we could address Daikin as a group ? Kind of petition or so ? Kind of uniform letter that each of us can send to a specific Daikin email address ?

**Comment by Apollon77** [comment]
Ok as update: I got a reply from the developer portal Daikin guys and will have a call with them within next 2 weeks ... lets see how this will be.

**Comment by jwillemsen** [comment]
I have exchanged a few emails with the daikin developer portal guys, their feedback really helped to migrate my HA daikin integration to the new setup

**Comment by jwillemsen** [comment]
Just made a small addition to my forked version to log the max and remaining day/minute limits when debugging is enabled, makes it easier to see how fast we are consuming our limits

**Comment by jwillemsen** [comment]
@Daikin-Europe would it be possible to depend the limits on the amount of devices the use has, with 4 units, just turning them on and change the setpoint I have 8 calls within a minute, which is higher as the minute limit of 6

**Comment by Raspdomo** [comment]
Some realistic frequency counts (based on my experience):
- reading indoor temperature and compressor frequency: every minute. Could reduce that to every 5 minutes at daytime and every 15 minutes at nighttime. Roughly 200-250 calls per day MINIMUM.
- 6-10 setpoint updates: morning and evening, coming/leaving home + extra setpoint updates overnight during cold winter nights to pre-heat rooms
- setpoint updates depending on solar production and internal (house) consumption: between 0 (clouded day) and 20 (varying clouds/sun)
Obviously these calls aren't spread evenly over 24h.

So 250-300 calls per day **PER UNIT** seems feasible (but too bad if your automated system has consumed them all => your system doesn't go into nightmode in the evening and keeps consuming...). And no minimum interval between calls. 
I have 7 units (+ 1 that already has the non-API WiFi module and that I sadly can't control over LAN).
That's about 2000 calls.
Even if the gathering of room temperatures for all units could be handled in one call, I'd still face 650 calls.

@Daikin-Europe: the limit of 200 (150 previously) doesn't seem to be based on any real home automation experience. Or did you overlook that some consumers have bought more than 1 unit ??

I think nobody can disagree that more and more houses will get automated in the near future,
Does Daikin choose to be the (leading) brand who does NOT offer a decent solution to support that ?
Once again @Daikin-Europe: why on earth are you suppressing a mature and good working local (LAN) API interface  that has no cost at all for you neither on processing nor storage "in the cloud" ?

**Comment by simonebortolin** [comment]
> Once again @Daikin-Europe: why on earth are you suppressing a mature and good working local (LAN) API interface that has no cost at all for you neither on processing nor storage "in the cloud" ?

Read. there is no point in posting the same questions over and over again, just read

https://community.home-assistant.io/t/daikin-integration-updated-2022-09-26/431819

**Comment by VolkerH** [comment]
> Read. there is no point in posting the same questions over and over again, just read

Yes, there is. The things that are mentioned in the link you posted can be changed by @Daikin-Europe. Non of this is irreversible.
The more people who let @Daikin-Europe know we are dissatisfied customers, the better. 
@Daikin-Europe can push out updates for the WIFI modules, I don't think a firmware update that enables local access on the newer devices is technically infeasible. If it is politics between @Daikin-Europe and Daikin Japan, they need to push back harder against the parent company. With more customer feedback, they can make a much stronger point.

I also have a use case where I wan't to control 5 devices based on PV excess production (mostly summer cooling and heating in spring/autumn) and tibber pricing (winter heating) + using external temperature sensors for better thermostat control.  No way this is possible with a rate limit of a few 100 calls/day.

It is good news that some of the developers now managed to establish contact with Daikin, so maybe we can use the cloud API.

@Apollon77, I can also see the devil's advocates points, in particular about remote access for non-technical users or possible warranty issues due to driving hardware to its limits (e.g. cycling on and off 1000s of times per hour which would probably not be good for the compressor). Thus, I can see good technical reasons for a rate limit, even in a local access mode. However, the one unit with old-style WLAN module I have that allows local access works equally well with cloud access, so the non-technical users still have that option if they don't want to set up local access. 

But completely regardless, what I take issue with is that I bought a device, not a service. @Daikin-Europe cannot cripple that device after they sold it. And I was quoted and sold air-conditioning units with _WiFi controller_, not with _cloud controller_.

**Comment by jwillemsen** [comment]
I have merged all changes for the new Developer Portal to the master branch of my fork, see https://github.com/jwillemsen/daikin_residential_altherma. Several users report back that they can see and control their Daikin devices using the new Developer Portal API but more user feedback is very welcome!

**Comment by barryvdh** [comment]
Is that also for the aircos, or is that still this Library?

**Comment by Raspdomo** [comment]
@jwillemsen: what happens when you bump into the limit (max calls per hour/day reached) ?

**Comment by jwillemsen** [comment]
Haven't tried it explicitly, but when reading comments from others you can't control the devices and get data updates until the next timeframe

**Comment by Raspdomo** [comment]
OMG... In Belgium there is an electricity tax on "peak power consumption per 15 minutes". So you want to keep that low. Cutting the oven or cooker power isn't really an option so I cut down on airco units (I heat with my aircos). I set the airco setpoints just below room temperature (= stops the units) until the situation gets back to normal. Usualy that's 5 - 10 minutes later. I then bring them up again, one per minute. 8 units = 24 calls (1 temp reading, 2 setpoint adjusts) over 10-15 minutes ! Happens 1-2 times per day.
Seems Faikin is going to do good business...

**Comment by jwillemsen** [comment]
I made the suggestion to @Daikin-Europe to make the limit dependent on the number of devices someone has, that allows a lot more use cases. Or provide a separate limit for polling the status and sending commands to a device (again per device).

**Comment by Raspdomo** [comment]
Both suggestions really make sense. The more units you have the more you've paid... 56 calls for sending commands is ridiculously low for my 8 units... Many many thanks for all your efforts !

**Comment by Apollon77** [comment]
I had a very constructive exchange with the Daikin Developer Portal contacts about several integration topics. So for me as a plugin developer I took the following results out of or conversations that I want to share for you:

* There will be rate limits on the cloud APIs because they also cost money for Daikin, so we should try our best to limit the calls best possible in the integrations.
* The rate limits per minute will be increased to 20/minute with an update of their cloud systems, most likely in march
* So we should implement dynamic polling intervals based on time or also maybe on activation status (poll less frequently when devies are off. That could make sense if the Onecta app is not used aside)
* After sending a call to the device it most likely takes 20-30s for the cloud values to be updated (older wifi controllers are slower), so this could be considered when polling the status after sending a command.
* To prevent hardware reliability issues it should be a common best practice to have at least 10 minutes between on and off calls, so turning it on or off faster could be very bad for the compressor and other hardware parts.
* Maybe also use dynamic polling depending on the command that was sent (e.g. temperature change vs mode change where more data are updated on the device)
* For Altherma devices there will be soon a local modbus module available that could be purchased and gives local modbus access to the data at much higher frequencies. Documentation can already be found on the internet (look for Daikin HomeHub) So this device should be preferred for "real time" data interactions.

I will also update the JavaScript libraries in the next weeks.

**Comment by Raspdomo** [comment]
@Apollin77: many thanks for all your efforts !
My 2 cents:
- cloud calls cost money indeed.That's why I refuse to understand why Daikin is abandoning a local (LAN) API. Then still, I understand data gathering for all units can be already done in 1 call. Great. Then why not offer a possibility to group multiple updates for 1 unit (e.g. turn on and set setpoint for the unit) in 1 call - or even updates for multiple units in 1 call ?
- do you mean 20 per minute or 20 per hour ? 20 per hour would be fine. PER INDOOR UNIT.
- dynamic polling: fine. Of course. PER INDOOR UNIT please ! The whole thing seems to be set up for a single split configuration, nobody in Daikin seems to have thought about multisplit...
- 10 minutes between calls for compressor protection purpose: fine. But first of all Daikin should protect the outdoor unit internally against that (that's how it is implemented on my Daikin heat pump boiler :-). WIth the IR remore you can send umpteen updates per minute (and I've heard stories of hotels where kids regularly do mess up).
And then again multisplit seems to be overlooked. Stopping/starting an indoor unit doesn't mean stopping/starting the outdoor unit also ! In multisplit you can easily have situations where one call per 10 minutes stops/starts the compressor each time, and situations with one call every minute that just keeps the outdoor compressor running quite steadily (= my real life observation).

Finally the feedback about Altherma totally confuses me. Daikin is qoing to provide a modbus for local access. But they are discarding their local access to airco units (BRP069C4x WiFi module) ????????????????

**Comment by Raspdomo** [comment]
20/min > I guess this is a protection against buggy/looping software generating tons of calls.
I don't see any functional need for so many calls in a single minute.

**Comment by Apollon77** [comment]
@rgerhards we touched several ideas from this thread in our conversation and they saw them all basically, also the subscription idea. I'm sure the Daikin guys think about some of them already. But in fact it's too easily for concrete feedback. 

As they also said it is just the beginning of the developer portal, so let's assume that some of the ideas could come up later on their roadmap ... but I think it is too early to say what and when.
But they were open to our feedback - at least how I saw it.

**Comment by Raspdomo** [comment]
"_But they were open to our feedback - at least how I saw it._" => that is the most promising statement of this whole thread :-)

SO MANY THANKS !

**Comment by jwillemsen** [comment]
Thanks for your update @Apollon77! The dynamic polling intervals is on my todo list for the HA integration (see https://github.com/jwillemsen/daikin_residential_altherma/issues/36). 

The Daikin HomeHub sounds interesting, but that is probably an expensive device and it again has to be installed, so all together not a cheap solution. And, it is another integration to implement within HA, again not a small effort, this Developer Portal change results also in a lot of work.

**Comment by rgerhards** [comment]
> The Daikin HomeHub sounds interesting, but that is probably an expensive device and it again has to be installed, so all together not a cheap solution. And, it is another integration to implement within HA, again not a small effort, this Developer Portal change results also in a lot of work.

I dug a bit into the home hub doc. As I understand it, it is not a vital solution for newer Altherma 3 units, because they come equipped with a WiFi interface. The doc says you can either connect the home hub xor the WiFi interface to the unit. Which also means, Daikin app support is not possible if you connect home hub.

All in all, this looks a bit like a lame excuse (sorry for being blunt).

**Comment by rospogrigio** [comment]
> Thank you @Apollon77 for the update! Am I understanding that you didn't talk about local LAN control at all?

@Apollon77 you did not reply to my question, did you even had the opportunity to discuss about local LAN control? Anything to report about this topic? Thank you

**Comment by Apollon77** [comment]
@rospogrigio In fact from what I understood the decision to remove the local interface was not coming from Daikin Europe ... It might be that upcoming device generations re-introduce some local interface, but thats nothing were any concrete informations are available, so for now it is as it is ... But yes also here "they are aware of the topic" :-)

**Comment by hmaki** [comment]
@Apollon77 really appreciate your efforts here. And thanks to @Daikin-Europe for listening.

Did you by any chance touch on the subject of removed entities, eg. fan rotation speed, heat exhanger temperature and demand control? @jwillemsen had longer list in his PR https://github.com/jwillemsen/daikin_onecta/pull/33.

**Comment by hmaki** [comment]
> Sorry. No we did not. I will ask via email.

Thanks, the use case I have is to calculate "COP" on the fly using fan rotation speed, suction temperature and heat exchanger temperature. For demand control, it's nice to be able to alter the demand control effect based on outdoor temperature. Makes the operation of AC unit much more stable on mild weather.

**Comment by Webreaper** [comment]
> Sorry. No we did not. I will ask via email. 

While you're at it, can you ask if they can provide a COP entity for heatpumps?

**Comment by jwillemsen** [comment]
when reading the homehub docu it seems that it doesn’t provide the data to calculate a cop, no energy produced values.

**Comment by voltagex** [comment]
> There will be rate limits on the cloud APIs because they also cost money for Daikin

They chose that design.

If a "cloud" model is too expensive, provide the local option again with a note that if you want higher polling/monitoring rates, use the local API!

**Comment by jwillemsen** [comment]
I have released a v4.0.0 pre release of the Daikin Onecta integration, see https://github.com/jwillemsen/daikin_onecta/releases/tag/v4.0.0

**Comment by rgerhards** [comment]
@jwillemsen thx again for all your valuable work!

I just tried to install beta v4 on HA docker install, upgraded to docker latest also today.  I have some issues to get the integration activated. I followed the readme for the install. After HA restart, I could successfully start the dialog via "add integration" button. Interered my name and (email, password) which I also use for the Onecta app. Then, I got redirected to daikin.eu for login. This one did NOT work. No matter what I entered, it always came back with the same screen again - but no error message.

I also have a second account for onecta, which I alwo tried. So I discarded that try, I called the daikin site manually and could log in with my other account (which I think is the actual owner vs. user). Then I tried adding the integration again. This time it did not ask me for credentials, it connected to daikin.eu, which brought me straight to the authorization dialog (so far looked good). I permitted access, was redirected to HA and then only a small "Daiking onecta" window was presented with a close button.

After I closed it, I could not find it in the installed integration list. I thought this might be to the user ID differences. So I went to ./config/.storage/application_credentials and change the credentials to the one in use by the screen session. I restarted HA again and tried re-adding. Some thing as before - Daikin auth dialog appeared, accepted, got redirected, got the small Window but integration not in active integration.

Then I rebooted the client machine where I ran HA GUI. Retried, same result.

Inside the HA log I found:
```
2024-02-26 13:18:55.781 ERROR (MainThread) [homeassistant.helpers.config_entry_oauth2_flow] Token request for daikin_onecta_rgehards_adiscon_com failed (invalid_client): Client authentication failed.
```
So I am finally stuck. Is there maybe anything that I need to reset/clean-up before I retry? Did I misinterpret the three fields Daiking_onecta asks me about (I can't get that dialog back again, so I cannot say what exactly the labels were).

Sorry if some questions are pretty basic (like reset-to-known-good).

Any help would be deeply appreciated.

**Comment by jwillemsen** [comment]
The daikin_onecta integration should redirect to the daikin website, it doesn't ask for user/password. I each time remove the daikin_onecta integration from HA, when it ask what it should do with the user credentials I select to delete those, when you now add it again it should ask again for the client id/secret and redirect to the Daikin website.

**Comment by rgerhards** [comment]
> The daikin_onecta integration should redirect to the daikin website,

it does, but it asks for three things before I do so.

I cannot remove the integration from HA, because it is not in the installed list.

When I add the integration now, it immediately redirects me to Daikin, I permit access and then I get the dialog in the first screenshot:

![image](https://github.com/rospogrigio/daikin_residential/assets/1482123/4fe2dc59-6698-411b-ba8e-ceb6007d80be)

After I click "Link Account, I get this screenshot:

![image](https://github.com/rospogrigio/daikin_residential/assets/1482123/692177a7-2e0c-456c-a932-491f7cde4259)

I click close and after that I cannot find any trace of daikin_onecta in the active list of integrations.

Note that in `.storage/applications_credentials` I do have an entry for daikin_onecta.

**Comment by jwillemsen** [comment]
When you go to Settings/Devices & Services there are three buttons in the top right corner with "application credentials" when you click on that, go to that page and see if there are credentials cached, if so, remove them and try again

**Comment by jwillemsen** [comment]
Important is that the code is under custom_components/daikin_onecta, when you have a daikin_residential_altherma directory you should rename it, looks to be a limitation in HA related to translations

**Comment by jwillemsen** [comment]
Please create an issue in my project @rgerhards, that is easier for everyone

**Comment by rgerhards** [comment]
> Please create an issue in my project @rgerhards, that is easier for everyone

will do

**Comment by wittimagic** [comment]
@Daikin-Europe 
I paid a lot of money for 7 devices with wireless lan connection for control.
This winter there were 3 incidents where I woke up in the morning in a freezing cold house because the cloud service failed. This is not acceptable and could easily solved by offering a local api. This would reduce the queries towards your cloud service and enhance the functionality for home automation users.
I really don't see any good reason why there is no local api and why it is taking so long to provide it.

**Comment by Webreaper** [comment]
@wittimagic can you elaborate? The MMI (which runs the schedules and the heat pump etc) has a wired connection, and to my understanding doesn't need the cloud to operate. I was under the impression that the cloud is only required for the API and the smartphone app to talk to the MMI to control the device. So why would the cloud being offline leave you with a cold house? 

If the basic schedule/heating functions of the heat pump require an internet connection and the cloud service to be running, then that is very much a problem, but I didn't think that's how it works....

**Comment by wittimagic** [comment]
I am running a/c systems ("Emura") to heat the house. The device schedules need the cloud service for every individual setting.

**Comment by Raspdomo** [comment]
@Webreaper the airco WiFi module BRP069C4x hasn't even got a LAN API anymore....... I have one of those, and 7 other airco units that still have a local LAN API. **I do not want to lose that functionality !!** So I do not want to have the firmware updated (which happens via Onecta and until now required an explicit end user approval) if that discards the local LAN API.

**Comment by sm-Fifteen** [comment]
Somewhat off-topic, but would it be preferable at this point (if buying a new heatpump/equipping an existing heatpump with a new adapter) to go for stock [AirZone Aidoo](https://www.airzonecontrol.com/na/en/control-solutions/aidoo/zigbee/) adapters instead of the ones Daikin are selling for Onecta/Comfort Control? The DKN Cloud Wi-Fi adapter for ductless (BRP072A43?) is refered to as [ AZAI6WSC__DKB__ ](https://backend.daikincomfort.com/docs/default-source/product-documents/commercial/manual/operation-manuals/iom_dkns-2101.pdf) in [some of](https://backend.daikincomfort.com/docs/default-source/product-documents/residential/brochures/cb-emurasz.pdf) Daikin's [material](https://backend.daikincomfort.com/docs/default-source/product-documents/residential/brochures/pf-dkncloud-smz.pdf), and appears to be identical to a [AZAI6WSC__DA0__](https://www.airzonecontrol.com/na/en/support/technical-details/aidoo-wi-fi-daikin-residential/), probably with some sort of custom firmware. The same goes for their Daikin Plus adapter, which is a AZAI6**WSP**DK__C__. I can't find much info on the BRP084Cxx or BRP069Cxx controllers and can't see them listed in the [publically available documents](https://backend.daikincomfort.com/docs/default-source/product-documents/commercial/manual/engineering-manuals/em_vrv-controls.pdf) I can put my hands on, strangely enough.

The main reasons to go for the official adapter appears to be energy monitoring, horizontal louver control and mode control (powerful mode and eco mode, namely), among all the other  advanced settings AirZone don't touch/read, but... even [those look limited](https://backend.daikincomfort.com/docs/default-source/product-documents/commercial/guide/pm-controls-fg.pdf), and with all the ongoing issues of going cloud-only, breaking the API, removing sensors, limiting polling rates, and other shenanigans, even those few extras make the offer look mightily unappealing.

EDIT: I ended up gonig with ESP32-Faikin controllers, which seemed like the least compromising mean of controlling my systems remotely. I still find it staggering for incoherent and confusing Daikin's offer for remote controllers is. Even Daikin's flagship Daikin One solution loses you things like Comfort Airflow and Powerful mode. The Airzone controllers are even more of a step down because they don't support basic things like horizontal swing. The European controllers this thread is about have now lost local control through an update, and are therefore useless. None of the S21 control systems can account for auto-setback from the presence sensor ("Intelligent eye mode") or configure it, which seems to be something reserved for P1P2 wired controllers like the Nav controller or Madoka/Stylish, which are not available on most residential units.

All official solutions seemed to come with compromises, so I went with the unofficial one.

**Comment by wittimagic** [comment]
I asked Daikin if there are any plans for a local API in the future and this was the answer:
_"Laut meinen Informationen ist es momentan nicht geplant die lokale API wieder bereitzustellen."_
-> to his knowledge there are no plans to bring back a local API

Daikin is **not** listening to their customers or simply ignoring them.

**Comment by ptz0n** [comment]
**Humble brag incoming;** I'm exited to share my service built on the new official API - **[Cloud smart grid for Daikin](https://daikin.erikeng.se)**

<img width="537" alt="Screenshot 2024-03-03 at 00 52 58" src="https://github.com/rospogrigio/daikin_residential/assets/200250/61e416c2-dc8c-4c09-8495-a0e51687c137">

_Key takeaway: current rate limit is not an issue for this use case._

**Comment by jwillemsen** [comment]
@hundsboog please open an issue an attach the device diagnostics and a run with debug enabled (see readme) strange that you only see a temperature

**Comment by hundsboog** [comment]
@jwillemsen thank you for your highspeed response! I try what you recommend. But should it normally work? This unit is really brand new...

**Comment by jwillemsen** [comment]
It could be that you have a device with some features my code doesn’t support @hundsboog, it is a lot of work to handle all possible devices

**Comment by climaJoe** [comment]
At least one thing should be provided in every case (please, thanks :)) and that is: The HTTP.GET Request via local API to let the owners read the data of THEIR devices as often its necessary for them. There are many good reasons for this (and really no single one against). 

1) Daikin would not loose any control or overview about the devices and their setups.
2) In the relationship between reading Data via GET and writing Data via PUT GET is very much oftener done, before an actually change of the device is finally made. So this much more oftener acts would be done localy and wouldn'd kost daikin absolutly nothing. 
3) Even the very tight limited cloudrequests would perhaps work if you only have to go via cloud for changing the device. 
4) The main stress for the cloudserver would be disappeared and so it would be a win-win-situation for both sides. 
5) Only HTTP.GET-Request via local API cannot change, overextend or damage the device so Daikin wouldn'd have any disadvantage with such a regulation. 

Without a free HTTP.GET-Request -function via local API the whole becomes a shicanery stuff which is not really recommendable.

**Comment by VolkerH** [comment]
It appears @Daikin-Europe broke the old API today. I guess it's time to install those Faikin boards on the weekend.

**Comment by wittimagic** [comment]
I am thinking about buying those as well or alternatively building them myself via esp32.
The rate limit counts per account and having 7 indoor units for heating naturally eats up more queries, because individual unit changes happen more often, e.g.
- bathroomt opening window after taking a shower or taking a dump
- getting fresh air in the living room
- opening the kitchen windows during or after cooking 
- switching the fan mode to silent during quiet hours
and other scenarios including changing the comfort temperature.

I already hit the limit without doing something weird during the day. This is really very annoying.

I requested a higher limit for my account but Daikin is not answering my mail request.

The situation is very sad and I really don't understand why Daikin is not offering a local API for their customers as a alternative.

@Daikin-Europe Your are heading in a wrong direction with this strategy ! What do you expect is going to happen ?

**Comment by rgerhards** [comment]
@Daikin-Europe I just wanted to let you and other know why a a) local interface is vital and b) the current rate limit really is far too low. We need to have one, at least two minute query intervals to gather stats sufficently relevant to optimize a system.

Have a look at some graphs from my system, which is equipped with my own external sensors. Without them, understanding what the machines does is very hard and insufficient to do any optimization and even less for controling the unit (e.g. solar or temperature boost).

I thought sharing a real-world use case may be useful. Note that the graph shown is only a subset of what I have.

![image](https://github.com/rospogrigio/daikin_residential/assets/1482123/acec8e94-3fea-4a54-8ee4-5f965c3e72d2)

**Comment by ImHereBecauseOfNewDaikinAPI** [comment]
@Daikin-Europe bring the local API back, make no sense to pull cloud for retrieving local data!

**Comment by wittimagic** [comment]
Sad to see that Daikin is not willing to bring back any kind of local API.
Having multiple Units within the same account eats up the current cloud based rate limit for queries too fast. Any kind of intelligent home automation is not possible under this circumstances. 
Cloud based control is never as stabke as a local API and only works as long as the providing company decides that they are willing to provide functionality.

So for the time being my advice is:
Don't buy Daikin products.

@Daikin-Europe

**Comment by pjgoodall** [comment]
I am so disappointed in this. I cannot recommend their otherwise excellent
products because of this disrespectful treatment of their customers.

**Comment by Hexadecimalism** [comment]
This is absolutely insufferable @Daikin-Europe. Your company has basically removed features I selected your devices for. I can no longer use my automations whenever the internet is down (which happens more often than I'd like).

**Comment by pjgoodall** [comment]
The firmware was changed to remove local control Immediately after I
purchased the product. 👹

**Comment by Dirksteral** [comment]
@Daikin-Europe Today the installation of 3 Daikin AC units was completed at my home - not a cheap investment, obviously, and now I have to find out that API got changed again... 😡

**Comment by Ing-Dom** [comment]
what morons.
Party their new API while making it useless with that rate limit. Oh its about cost?
THEN WHY YOU FORCE US TO USE YOUR FUCKIN CLOUD SHIT ?
Bought Diakin ONLY because of that local api, only to find out (after installed) that it was gone..

**Comment by Daikin-Europe** [comment]
Dear Open-Source Community,

We want to announce a new feature to our developer portal: the launch of self-service functionality. 
Here's what you can do:

1. **Create Your Application**: Gain access to your own client ID and client secret credentials by creating your application. You can customize your app with a unique name, description, and redirect URI to suit your needs.
2. **Update App Specifications**: Easily modify your app's specifications as your project evolves. Whether it's tweaking the description or updating the redirect URI, you have the flexibility to make changes as necessary.
3. **Delete Your App**: Need to start fresh or no longer using an application? Simply delete it from your account with ease.

Integrations that were using the temporary client ID `emU20GdJDiiUxI_HnFGz69dD` will keep functioning till End of August before we revoke these credentials. Please create you own application and migrate on time to avoid any impact on your current integration. 

Ready to get started? Head over to our [Developer Portal](https://developer.cloud.daikineurope.com/) to explore this new feature.

**Comment by WegnerDan** [comment]
Does the self service client id have any implication on the rate limiting? 

And no word about local api access...

**Comment by tetele** [comment]
@Daikin-Europe lovely to see you address all concerns expressed in this thread. You can peacefully close the issue now. 🤦‍♂️

**Comment by wittimagic** [comment]
Tell your friends and everyone you know about this.
Advise them not to buy Daikin, point them to home automation and user friendly alternatives instead.

This is the only way to make them listening.

**Comment by WegnerDan** [comment]
> Advise them not to buy Daikin, point them to home automation and user friendly alternatives instead.

Do you have any suggestions for air conditioners that fit that criteria? As far as I know there aren't any

**Comment by Hexadecimalism** [comment]
I paid thousands for 5 units and their installation, only to have features I paid for taken away. This is absolutely insufferable.

**Comment by wittimagic** [comment]
> > Advise them not to buy Daikin, point them to home automation and user friendly alternatives instead.
> 
> Do you have any suggestions for air conditioners that fit that criteria? As far as I know there aren't any

Panasonic:
https://github.com/sockless-coding/panasonic_cc

Or Midea Group brands (Hualing, Senville, Klimaire, AirCon, Century, Pridiom, Thermocore, Comfee, Alpine Home Air, Artel, Beko, Electrolux, Galactic, Idea, Inventor, Kaisai, Mitsui, Mr. Cool, Neoclima, Olimpia Splendid, Pioneer, QLIMA, Rotenso, Royal Clima, Qzen, Toshiba, Carrier, Goodman, Friedrich, Samsung, Kenmore, Trane, Lennox, LG and much more):
https://github.com/mac-zhou/midea-ac-py

**Comment by jwillemsen** [comment]
I tried to create an application and setup the daikin_onecta integration using a new client id/secret, but it failed, am I the only one, or more people having the same issue?

**Comment by jwillemsen** [comment]
Got it to work with daikin_onecta after a restart, will make a new release with an updated readme.

**Comment by Frits1980** [comment]
It's funny. I'm in the market for a rather big AC system. But this is a big red flag. The way Daikin is toying around with it's customers is terrible. It's also killing innovation. The airconditioning market is in my opinion very conservative. Daikin just proved that by doing something other players in other markets did 10 years ago and paid the price for. I hope they wake up soon. But it will be too late for my system.

**Comment by trungbtsb60687** [comment]
onecta app discovered my daikin unit, but refused to connect. Its said the thailand region is not supported.
Is there a way to switch daikin wifi adapter to EU region? 
![z5721419144941_8219b98319a7157e748de0f503880e45](https://github.com/user-attachments/assets/f57ca7d8-62f6-48d6-bc64-86ed9276a843)
![z5721419182989_1d9b3d189ea4e96a1fdb5b2895c9ef8c](https://github.com/user-attachments/assets/d54b0f77-8ac5-4442-8705-985f256fb03e)
Thai region is supposed to go with daikin mobile controller app, but only onecta app can integrate with home assistant, isn't it.

**Comment by Apollon77** [comment]
I think you should contact Daikin for this question. We can not tell more

**Comment by carlosamus123** [comment]
Guys I also agree the rate limit of 200 a day is crazy low! I have come up with a work around while is not ideal.. it may allow you to do fine level controls without using up your rate limits, which will allow a more frequent polling interval as you will be splitting up 'controls' and 'data'  essentially.

Hear me out.. Alexa skill.. doesnt count towards your API calls..  link the onecta account to alexa

ensure you can turn your heating on/off as well as your water heater etc

now create home assistant booleans in this example I will use 
'ALEXA_HOTWATER', ALEXA_HOTWATER_PERFORMANCE, and ALEXA_HEATING  

these 3 can be exposed to Alexa. 

Once they are in alexa and the actions to turn them off and on,results in them turning on and off in both alexa and HA

now you can create multiple automations, one for when they turn on, and one for when they turn off

for example if the 'ALEXA_HOTWATER' is turned on in HA ( by an automation etc) then the action for alexa is to turn on the Onecta (linked) water heater  and so on

the delay is at most 3-5 seconds

Again its not perfect but losing the ability to control your devices due to the rate limit is less ideal! 

I hope I helped even just 1 person because i'm very happy with the outcome :)

**Comment by RadianM** [comment]
I'm desperately trying to 'get on board' with the new Onecta regime (i.e. learn to live with highly restrictive usage limits) but everything about Daikin's design seems to get in the way. Because I have Agile Octopus energy tariff, I need to be able to turn down (during expensive energy pricing periods), or turn up the A/C (during very cheap or even negative pricing periods). 

With Agile pricing, there are 48 half-hourly slots and I thought the most efficient way to do this would be to set up the three available schedules (think: cheap, medium, expensive) with appropriate temperature, fan speed, energy saving etc. parameters in the Onecta app. Then my HA automation can switch between schedules in one action at the appropriate pricing thresholds.

Except, when switching  schedules, no change in state is effected by the A/C until the next timed change in the schedule occurs. I had assumed the unit would say 'oh, a change of schedule - what should I be doing right now in this new schedule?) - but no, the Onecta app spells it out - "Next scheduled action..." showing some future time and state.

The only way this might be made to work is to put 48 entries in each schedule - but even then, there's likely going to be a half-hour lag in responding. Anyone facing a similar challenge?

**Comment by carlosamus123** [comment]
I am pretty sure the command to change a device settings is instant or at least should be. do you mean it does listen to your command but Home assistant wont show changes that fast?

I created an automation that refreshes the entity/device   here is the code  

action: homeassistant.update_entity
data:
  entity_id:
    - water_heater.altherma
    - climate.altherma_room_temperature


and it will instantly update those entities ( it will use one of your 200 requests)

**Comment by RadianM** [comment]
> do you mean it does listen to your command but Home assistant wont show changes that fast?

No, the command to switch schedules is issued and received instantly. The delay is that the Daikin units, while acknowledging the change in schedule, only obey the new schedule at the next scheduled change in the equipment's settings.

I had rather hoped the units would say to themselves 'I've just been switched to a new schedule... what should I be doing right now' rather than 'OK, my schedule just changed... I'll stay exactly the way I am now and defer changes to my settings until the next timed event'.

**Comment by carlosamus123** [comment]
Aah right. Then as a work around I would add in a change to the AC to
whatever the new schedule would/should do at the same time. So while it's
not picked up the new schedule yet by the time it does. It's already doing
what you wanted ?

Not ideal but there is always a way !

**Comment by RadianM** [comment]
OK, but the regular scheduling needs to be switched off for cheap/expensive price slots to prevent it overriding the changes. Then I guess the appropriate forced temperature/fan/economy setting for these conditions will have to be made. But then when the pricing lands between the upper and lower limits once again, I hope turning back on the normal schedule will make it change to the appropriate settings for that particular time - but I doubt it will (~~I can't test this at the moment~~ it doesn't) but if it doesn't, explicitly setting the parameters and duplicating them for each half hour slot is not even going to guarantee it makes the change on time.

I think the only practical way I can cater for the (rather complicated) normal schedule is to go beyond the simple UI automation setup and do something with pyscript. And then I might as well include the two extreme cases in that script. All this would be unnecessary if the schedule switchover was slightly more intelligent.

**Comment by carlosamus123** [comment]
I created a comprehensive heating automation. You could adapt it to AC I am
sure

Here is is  . It's designed to turn on main heating if any radiator  calls
for heat. And if all become  idle then main heating turns off. Which turns
off my heat pump .

You could let HA do all the scheduling and turn ac on or off based on other
events

alias: Main Heating Control
description: ""
triggers:
  - entity_id:
      - climate.landing_radiator_thermostat
      - climate.bathroom_radiator_thermostat
      - climate.phoebe_s_radiator_thermostat
      - climate.claires_radiator_thermostat
      - climate.wardrobe_radiator_thermostat
      - climate.office_radiator_thermostat
      - climate.kitchen_radiator_thermostat
      - climate.hallway_radiator_thermostat
      - climate.claire_s_toilet_radiator_thermostat
      - climate.living_room_radiator_thermostat
    attribute: hvac_action
    trigger: state
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ is_state_attr('climate.landing_radiator_thermostat',
              'hvac_action', 'heating') or
                 is_state_attr('climate.bathroom_radiator_thermostat',
'hvac_action', 'heating') or
                 is_state_attr('climate.phoebe_s_radiator_thermostat',
'hvac_action', 'heating') or
                 is_state_attr('climate.claires_radiator_thermostat',
'hvac_action', 'heating') or
                 is_state_attr('climate.wardrobe_radiator_thermostat',
'hvac_action', 'heating') or
                 is_state_attr('climate.office_radiator_thermostat',
'hvac_action', 'heating') or
                 is_state_attr('climate.kitchen_radiator_thermostat',
'hvac_action', 'heating') or
                 is_state_attr('climate.hallway_radiator_thermostat',
'hvac_action', 'heating') or

is_state_attr('climate.claire_s_toilet_radiator_thermostat', 'hvac_action',
'heating') or
                 is_state_attr('climate.living_room_radiator_thermostat',
'hvac_action', 'heating') }}
        sequence:
          - target:
              entity_id: input_boolean.alexa_heating
            action: input_boolean.turn_on
            data: {}
      - conditions:
          - condition: template
            value_template: >
              {{ is_state_attr('climate.landing_radiator_thermostat',
              'hvac_action', 'idle') and
                 is_state_attr('climate.bathroom_radiator_thermostat',
'hvac_action', 'idle') and
                 is_state_attr('climate.phoebe_s_radiator_thermostat',
'hvac_action', 'idle') and
                 is_state_attr('climate.claires_radiator_thermostat',
'hvac_action', 'idle') and
                 is_state_attr('climate.wardrobe_radiator_thermostat',
'hvac_action', 'idle') and
                 is_state_attr('climate.office_radiator_thermostat',
'hvac_action', 'idle') and
                 is_state_attr('climate.kitchen_radiator_thermostat',
'hvac_action', 'idle') and
                 is_state_attr('climate.hallway_radiator_thermostat',
'hvac_action', 'idle') and

is_state_attr('climate.claire_s_toilet_radiator_thermostat', 'hvac_action',
'idle') and
                 is_state_attr('climate.living_room_radiator_thermostat',
'hvac_action', 'idle') }}
        sequence:
          - target:
              entity_id: input_boolean.alexa_heating
            action: input_boolean.turn_off
            data: {}

**Comment by GiedriusN1** [comment]
Hi, what is the best way to acces Daikin unit by LAN ?

**Comment by carl-hussain-bloom** [comment]
I looked into it and someth9ling called Faikin. But it's very involved.  I would suggest ypu get a powerline adapter that gives wifi. And use that wherever your daikin is and connect to that. This will ensure a strong connection. The amount of data it sends is minimal really so the wifi in the same room will sort it

**Comment by GiedriusN1** [comment]
> I looked into it and someth9ling called Faikin. But it's very involved. I would suggest ypu get a powerline adapter that gives wifi. And use that wherever your daikin is and connect to that. This will ensure a strong connection. The amount of data it sends is minimal really so the wifi in the same room will sort it

We dont have wifi for security reasons ...

**Comment by Webreaper** [comment]
> We dont have wifi for security reasons ...

Okay, I'll bite. What possible security reasons could there be to not have WiFi?

**Comment by carl-hussain-bloom** [comment]
Yes I am confused too. If you setup wpa3 it will be pretty secure.  And even if not secure what is so sensitive that you can't risk it being accessed?  Any IOT device can be used to hack your network if someone really wanted to. If you are online you are not safe. The only reason you are not compromised is because people don't know if you have anything of value :)

**Comment by GiedriusN1** [comment]
> > We dont have wifi for security reasons ...
> 
> Okay, I'll bite. What possible security reasons could there be to not have WiFi?

Wifi can be accessed from outside and hacked.

**Comment by Apollon77** [comment]
Come on guys, please lets stay on topic ... 
The whole topic here is about the Wifi interfaces of the Daikin devices. If Wifi is no option then the topic is wrong here.

**Comment by Webreaper** [comment]
This thread hasn't been on topic for months. It's just become a general dumping ground of issues and questions.

**Comment by Terabyte1385** [comment]
Popping in here to ask if there is any way the new Daikin models can be made to work on LAN? I have one of those with the BRP069C4x Wi-Fi control → connect to Onecta (cloud) and do not work with LAN afaik. Connecting to it directly via IP reveals that it still has port 80 open but it's only for licensing text.

**Comment by Neo2SHYAlien** [comment]
There is some endpoints for generating debug information but nothing useful in the term of local control

**Comment by VolkerH** [comment]
@Terabyte1385 ... check out Faikin modules
